title: The Umbral Archive
author: Lord Deusin Amradyr
description: >
  A modest library found in a remote corner of the Shadowfell. It contains books of lore, arcana, history, and other esoteria curated by an eldritch librarian.

theme: minima